package com.crusaders.gauntlet.java.codeGenerationJava;

import java.io.File;

import com.crusaders.gauntlet.java.codeGeneration.ScriptGenerator;
import com.crusaders.gauntlet.java.fileManagement.CreatorDeletor;
import com.crusaders.gauntlet.java.fileManagement.FileCreatorDeletor;

public class ScriptGeneratorJava implements ScriptGenerator{
	
	private static int indexOfScript = 0;
	
	
	private final String directoryPath = "src/com/crusaders/gauntlet/scripts/autoGeneratedScripts/";
	private final String defaultName = "ActionOfMacro";
	private final String extentionOfFile = ".txt";
	
	private FileCreatorDeletor creator;
	private File actionScript;
	
	public ScriptGeneratorJava() {
		initDependecies();
		indexOfScript++;
	}
	
	private void initDependecies() {
		creator = new CreatorDeletor();
		actionScript = new File(directoryPath + defaultName+ indexOfScript + extentionOfFile);
	}

	@Override
	public int getNextIndex() {
		return indexOfScript+1;
	}

	@Override
	public String getPath() {
		return directoryPath;
	}

	@Override
	public boolean generateNewScript() {
		creator.createFile(actionScript, directoryPath);
		return false;
	}


}
