package com.crusaders.gauntlet.java.util;

public class Direction {
    
	//This object wil be generated by the data received from the Arduino 
	//accX and accY measure the gravitational accelerations at the sensor
	private int accX, accY;
	
	public Direction(int accX,int accY)
	{
		this.accX = accX;
		this.accY = accY;
	}

	public int getAccX() {
		return accX;
	}

	public void setAccX(int accX) {
		this.accX = accX;
	}

	public int getAccY() {
		return accY;
	}

	public void setAccY(int accY) {
		this.accY = accY;
	}
	
	
}
